// Generated by tools/build_glow_digits.py - do not edit.
// Offset of every glow-digit bitmap's top-left from (pen x, line top) of the cg_time font,
// and the cell size. Same for every digit because all are emitted on one uniform cell.
// Y0 includes the +1 row calibration CIQ applies to font glyphs (see Y_CALIBRATION).
module GlowTimeMetrics {
    const X0 = -18;
    const Y0 = 28;
    const W = 119;
    const H = 138;
}
