// Generated by tools/build_arc_font.py - do not edit.
// Screen top-left of each battery-arc dash glyph (cg_arc, 454 px screen), dash 0 = left.
module ArcMetrics {
    const X = [100, 115, 130, 146, 162, 179, 196, 213, 230, 246, 261, 277, 293, 308, 322, 336];
    const Y = [32, 24, 17, 11, 6, 3, 0, 0, 0, 0, 3, 6, 11, 17, 24, 32];
}
