// Generated by tools/build_arc_font.py - do not edit.
// Screen top-left of each battery-arc dash glyph (cg_arc, 454 px screen), dash 0 = left.
module ArcMetrics {
    const X = [102, 116, 131, 147, 163, 180, 196, 213, 229, 245, 261, 276, 292, 306, 321, 335];
    const Y = [35, 27, 20, 14, 9, 6, 3, 3, 3, 3, 6, 9, 14, 20, 27, 35];
}
