// Generated by tools/build_fonts_grid.py - do not edit.
// Screen px the cg_time digit INK centre sits below a TEXT_JUSTIFY_VCENTER anchor
// (IBM Plex Mono 153 px: ink rows 48-159 in a 200 px line box, +1 for CIQ's glyph row offset).
// The view subtracts it so the time's y is the centre of the digits themselves.
module TimeInk {
    const DY = 5;
}
