// Generated by tools/build_glow_time.py - do not edit.
// Offset of every glow-glyph bitmap from (pen x, line top) of stm_time; Y0 includes +1 for
// CIQ's glyph row offset.
module GlowTimeMetrics {
    const X0 = -18;
    const Y0 = 0;
}
